FROM php:7.3-alpine

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.tuna.tsinghua.edu.cn/g' /etc/apk/repositories

RUN apk add --no-cache \
        freetype libpng libjpeg-turbo \
        libpng-dev \
        libjpeg-turbo-dev \
        libzip-dev \
        freetype-dev; \
    docker-php-ext-configure gd --with-gd \
        --with-freetype-dir=/usr/include/ \
        --with-jpeg-dir=/usr/include/ \
        --with-png-dir=/usr/include/; \
    docker-php-ext-install pdo pdo_mysql bcmath gd zip; \
    apk del --no-cache freetype-dev libpng-dev libjpeg-turbo-dev;

# RUN composer config -g repo.packagist composer https://mirrors.aliyun.com/composer/
